
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

<<<<<<< HEAD
#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
=======
#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
<<<<<<< HEAD
static yyconst flex_int16_t yy_accept[206] =
    {   0,
        0,    0,   87,   85,   84,   83,   73,   85,   63,   67,
       85,   75,   78,   61,   59,   66,   60,   72,   62,   34,
       65,   64,   81,   68,   82,   74,   33,   76,   79,   71,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   77,   70,   80,   69,   46,
        0,   37,   51,   47,   56,    0,   49,   39,   52,   40,
       53,   38,   50,    0,   34,   41,   43,   45,   44,   42,
       33,   57,   33,   33,   33,   33,   33,   33,    8,   33,
       33,   33,   33,   33,   33,   16,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   58,   48,   36,

       35,   54,   55,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   14,   33,   17,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,    1,   33,    3,    4,   33,   33,   33,   33,
       10,   11,   33,   33,   15,   18,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   30,   33,   33,
        2,    5,   33,   33,   33,   33,   13,   33,   33,   21,
       33,   33,   33,   33,   33,   33,   28,   33,   33,   32,
       33,   33,    9,   12,   33,   20,   22,   23,   24,   25,
       26,   33,   33,   33,   33,    7,   33,   27,   33,   33,

        6,   19,   29,   31,    0
=======
static yyconst flex_int16_t yy_accept[205] =
    {   0,
        0,    0,   86,   84,   83,   73,   84,   63,   67,   84,
       75,   78,   61,   59,   66,   60,   72,   62,   34,   65,
       64,   81,   68,   82,   74,   33,   76,   79,   71,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   77,   70,   80,   69,   46,    0,
       37,   51,   47,   56,    0,   49,   39,   52,   40,   53,
       38,   50,    0,   34,   41,   43,   45,   44,   42,   33,
       57,   33,   33,   33,   33,   33,   33,    8,   33,   33,
       33,   33,   33,   33,   16,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   58,   48,   36,   35,

       54,   55,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   14,   33,   17,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,    1,   33,    3,    4,   33,   33,   33,   33,   10,
       11,   33,   33,   15,   18,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   30,   33,   33,    2,
        5,   33,   33,   33,   33,   13,   33,   33,   21,   33,
       33,   33,   33,   33,   33,   28,   33,   33,   32,   33,
       33,    9,   12,   33,   20,   22,   23,   24,   25,   26,
       33,   33,   33,   33,    7,   33,   27,   33,   33,    6,

       19,   29,   31,    0
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
<<<<<<< HEAD
        1,    3,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       25,   26,   27,   28,   26,   26,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   24,   38,   39,   40,   41,
       42,   43,   24,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,    1,    1,    1,    1,
=======
        1,    1,    3,    4,    1,    1,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,   22,    1,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       24,   25,   26,   27,   25,   25,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   23,   37,   38,   39,   40,
       41,   42,   23,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,    1,    1,    1,    1,
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

<<<<<<< HEAD
static yyconst flex_int32_t yy_meta[57] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    1,    3,    2,    2,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[209] =
    {   0,
        0,    0,  219,  220,  220,  220,  197,  212,  195,   50,
        0,  220,  220,  194,   46,  220,   47,  220,  193,   45,
      220,  220,   43,  192,   44,  220,    0,  220,  220,  191,
      164,  166,   41,   39,   34,   37,  167,   44,  166,  174,
       50,  155,  164,  162,  167,  220,   38,  220,  220,  220,
      197,  220,  220,  220,  220,  193,  220,  220,  220,  220,
      220,  220,  220,  183,   65,  178,  220,  220,  220,  177,
        0,  220,  151,  163,  150,  165,  152,  158,  144,  145,
      142,  142,  145,  142,  139,    0,  138,  142,   54,  140,
       39,   59,  144,  137,   53,   56,  142,  220,  220,  220,

      161,  220,  220,  135,  147,  142,  130,   56,  144,  142,
      138,  130,  136,  139,    0,  125,    0,  131,  128,  117,
      119,  121,  128,  114,  112,  112,  124,  114,  118,  122,
      124,  113,    0,  113,    0,    0,  104,  112,  101,  108,
        0,    0,  102,   99,    0,    0,   99,   99,   96,  108,
       98,  102,  107,  106,  104,   94,   99,    0,   87,   99,
        0,    0,   90,   91,   96,   87,    0,   81,   85,    0,
       93,   90,   92,   76,   85,   87,    0,   78,   81,    0,
       70,   70,    0,    0,   82,    0,    0,    0,    0,    0,
        0,   80,   80,   73,   78,    0,   66,    0,   77,   64,

        0,    0,    0,    0,  220,  103,   91,  105
    } ;

static yyconst flex_int16_t yy_def[209] =
    {   0,
      205,    1,  205,  205,  205,  205,  205,  206,  205,  205,
      207,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  208,  205,  205,  205,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  205,  205,  205,  205,  205,
      206,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      208,  205,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  205,  205,  205,

      205,  205,  205,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,

      208,  208,  208,  208,    0,  205,  205,  205
    } ;

static yyconst flex_int16_t yy_nxt[277] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,    4,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   27,   38,   27,   39,   27,
       27,   27,   27,   40,   41,   42,   43,   44,   45,   27,
       27,   27,   46,   47,   48,   49,   54,   58,   98,   64,
       60,   65,   66,   67,   69,   70,   59,   61,   62,   75,
       55,   78,   80,  122,   81,   83,   76,   86,   84,   64,
       79,   65,   77,   82,   87,   90,   91,  124,  119,  128,
      123,   99,  130,   56,  131,   92,  204,  129,   93,  120,

      137,  138,  125,   51,   51,   51,   71,   71,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  140,  139,  136,  135,  134,  133,  101,  132,  127,
      126,  121,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,

      100,   52,   97,   96,   95,   94,   89,   88,   85,   74,
       73,   72,   68,   63,   57,   53,   52,   50,  205,    3,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205
    } ;

static yyconst flex_int16_t yy_chk[277] =
=======
static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    3,    2,    2,    2,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[208] =
    {   0,
        0,    0,  218,  219,  219,  197,  212,  195,   50,    0,
      219,  219,  194,   46,  219,   47,  219,  193,   45,  219,
      219,   43,  192,   44,  219,    0,  219,  219,  191,  164,
      166,   41,   39,   34,   37,  167,   44,  166,  174,   50,
      155,  164,  162,  167,  219,   38,  219,  219,  219,  197,
      219,  219,  219,  219,  193,  219,  219,  219,  219,  219,
      219,  219,  183,   65,  178,  219,  219,  219,  177,    0,
      219,  151,  163,  150,  165,  152,  158,  144,  145,  142,
      142,  145,  142,  139,    0,  138,  142,   54,  140,   39,
       59,  144,  137,   53,   56,  142,  219,  219,  219,  161,

      219,  219,  135,  147,  142,  130,   56,  144,  142,  138,
      130,  136,  139,    0,  125,    0,  131,  128,  117,  119,
      121,  128,  114,  112,  112,  124,  114,  118,  122,  124,
      113,    0,  113,    0,    0,  104,  112,  101,  108,    0,
        0,  102,   99,    0,    0,   99,   99,   96,  108,   98,
      102,  107,  106,  104,   94,   99,    0,   87,   99,    0,
        0,   90,   91,   96,   87,    0,   81,   85,    0,   93,
       90,   92,   76,   85,   87,    0,   78,   81,    0,   70,
       70,    0,    0,   82,    0,    0,    0,    0,    0,    0,
       80,   80,   73,   78,    0,   66,    0,   77,   64,    0,

        0,    0,    0,  219,  102,   90,  104
    } ;

static yyconst flex_int16_t yy_def[208] =
    {   0,
      204,    1,  204,  204,  204,  204,  205,  204,  204,  206,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  207,  204,  204,  204,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  204,  204,  204,  204,  204,  205,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  207,
      204,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  204,  204,  204,  204,

      204,  204,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,    0,  204,  204,  204
    } ;

static yyconst flex_int16_t yy_nxt[275] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,    4,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   26,   37,   26,   38,   26,   26,
       26,   26,   39,   40,   41,   42,   43,   44,   26,   26,
       26,   45,   46,   47,   48,   53,   57,   97,   63,   59,
       64,   65,   66,   68,   69,   58,   60,   61,   74,   54,
       77,   79,  121,   80,   82,   75,   85,   83,   63,   78,
       64,   76,   81,   86,   89,   90,  123,  118,  127,  122,
       98,  129,   55,  130,   91,  203,  128,   92,  119,  136,

      137,  124,   50,   50,   50,   70,   70,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  135,  134,  133,  132,  100,  131,  126,  125,
      120,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,

       51,   96,   95,   94,   93,   88,   87,   84,   73,   72,
       71,   67,   62,   56,   52,   51,   49,  204,    3,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204
    } ;

static yyconst flex_int16_t yy_chk[275] =
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
<<<<<<< HEAD
        1,    1,    1,    1,    1,    1,   10,   15,   47,   20,
       17,   20,   23,   23,   25,   25,   15,   17,   17,   33,
       10,   34,   35,   91,   35,   36,   33,   38,   36,   65,
       34,   65,   33,   35,   38,   41,   41,   92,   89,   95,
       91,   47,   96,  207,   96,   41,  200,   95,   41,   89,

      108,  108,   92,  206,  206,  206,  208,  208,  199,  197,
      195,  194,  193,  192,  185,  182,  181,  179,  178,  176,
      175,  174,  173,  172,  171,  169,  168,  166,  165,  164,
      163,  160,  159,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  144,  143,  140,  139,  138,  137,
      134,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  116,  114,  113,  112,
      111,  110,  109,  107,  106,  105,  104,  101,   97,   94,
       93,   90,   88,   87,   85,   84,   83,   82,   81,   80,
       79,   78,   77,   76,   75,   74,   73,   70,   66,   64,

       56,   51,   45,   44,   43,   42,   40,   39,   37,   32,
       31,   30,   24,   19,   14,    9,    8,    7,    3,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205
=======
        1,    1,    1,    1,    1,    9,   14,   46,   19,   16,
       19,   22,   22,   24,   24,   14,   16,   16,   32,    9,
       33,   34,   90,   34,   35,   32,   37,   35,   64,   33,
       64,   32,   34,   37,   40,   40,   91,   88,   94,   90,
       46,   95,  206,   95,   40,  199,   94,   40,   88,  107,

      107,   91,  205,  205,  205,  207,  207,  198,  196,  194,
      193,  192,  191,  184,  181,  180,  178,  177,  175,  174,
      173,  172,  171,  170,  168,  167,  165,  164,  163,  162,
      159,  158,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  143,  142,  139,  138,  137,  136,  133,
      131,  130,  129,  128,  127,  126,  125,  124,  123,  122,
      121,  120,  119,  118,  117,  115,  113,  112,  111,  110,
      109,  108,  106,  105,  104,  103,  100,   96,   93,   92,
       89,   87,   86,   84,   83,   82,   81,   80,   79,   78,
       77,   76,   75,   74,   73,   72,   69,   65,   63,   55,

       50,   44,   43,   42,   41,   39,   38,   36,   31,   30,
       29,   23,   18,   13,    8,    7,    6,    3,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../lexer/cLexer.l"
/*
File: cLexer.l
Created: September 27, 2015
Last Modified: October 15, 2015
Class: CS 460 (Compiler Construction)

This is the input file to Flex that will be used in the front end of our
compiler. 

The lexer is responsible for two main tasks:
1. Scan for tokens and pass these tokens to the parser for syntax analysis.
2. Place as much information into the symbol table as possible. Some of tihis
responsibility is left to the parser. 

Tokens have been declared by Bison and are included in the file 
"cParser.tab.h."
*/
/* lexer definitions */
#line 21 "../lexer/cLexer.l"
	/* includes */
	#include <iostream>
	#include <string>
	#include "stdlib.h"
	#include <climits>
	#include <fstream>
	#include "../parser/cParser.tab.h"
	#include "../classes/symbolTable.h"

	/* externs */
	extern bool LFLAG; 
	extern std::ofstream outL; 
	extern void yyerror(const char* errorMsg);
	bool inInsertMode = true; // false => "lookup mode"
	dVal* temp = NULL; 

	/* variables */
	int colPosition = 0;
	int tabCount = 0; 
	symbolTable table;
<<<<<<< HEAD
	std::string currentSourceCodeLine = ""; 
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
	std::vector<std::string> sourceCode;  
/* token definitions */
/* tell flex to read only one input file - THIS COULD CHANGE */
/* rules and actions */
<<<<<<< HEAD
#line 634 "lex.yy.c"
=======
#line 633 "lex.yy.c"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
<<<<<<< HEAD
#line 59 "../lexer/cLexer.l"


#line 824 "lex.yy.c"
=======
#line 58 "../lexer/cLexer.l"


#line 823 "lex.yy.c"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
<<<<<<< HEAD
				if ( yy_current_state >= 206 )
=======
				if ( yy_current_state >= 205 )
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
<<<<<<< HEAD
		while ( yy_base[yy_current_state] != 220 );
=======
		while ( yy_base[yy_current_state] != 219 );
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
<<<<<<< HEAD
#line 61 "../lexer/cLexer.l"
=======
#line 60 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< AUTO >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return AUTO; 
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
<<<<<<< HEAD
#line 69 "../lexer/cLexer.l"
=======
#line 66 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< BREAK >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return BREAK; 
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
<<<<<<< HEAD
#line 77 "../lexer/cLexer.l"
=======
#line 72 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << " < CASE >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return CASE; 
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
<<<<<<< HEAD
#line 85 "../lexer/cLexer.l"
=======
#line 78 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< CHAR >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return CHAR; 
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
<<<<<<< HEAD
#line 93 "../lexer/cLexer.l"
=======
#line 84 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< CONST >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return CONST; 
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
<<<<<<< HEAD
#line 101 "../lexer/cLexer.l"
=======
#line 90 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< CONTINUE >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return CONTINUE; 
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
<<<<<<< HEAD
#line 109 "../lexer/cLexer.l"
=======
#line 96 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< DEFAULT >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return DEFAULT; 
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
<<<<<<< HEAD
#line 117 "../lexer/cLexer.l"
=======
#line 102 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< DO >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return DO; 
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
<<<<<<< HEAD
#line 125 "../lexer/cLexer.l"
=======
#line 108 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< DOUBLE >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return DOUBLE; 
				}	
	YY_BREAK
case 10:
YY_RULE_SETUP
<<<<<<< HEAD
#line 133 "../lexer/cLexer.l"
=======
#line 114 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ELSE >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return ELSE; 
				}
	YY_BREAK
case 11:
YY_RULE_SETUP
<<<<<<< HEAD
#line 141 "../lexer/cLexer.l"
=======
#line 120 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ENUM >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return ENUM; 
				}
	YY_BREAK
case 12:
YY_RULE_SETUP
<<<<<<< HEAD
#line 149 "../lexer/cLexer.l"
=======
#line 126 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< EXTERN >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return EXTERN; 
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
<<<<<<< HEAD
#line 157 "../lexer/cLexer.l"
=======
#line 132 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< FLOAT >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return FLOAT; 
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
<<<<<<< HEAD
#line 165 "../lexer/cLexer.l"
=======
#line 138 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< FOR >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return FOR; 
				}
	YY_BREAK
case 15:
YY_RULE_SETUP
<<<<<<< HEAD
#line 173 "../lexer/cLexer.l"
=======
#line 144 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< GOTO >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return GOTO; 
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
<<<<<<< HEAD
#line 181 "../lexer/cLexer.l"
=======
#line 150 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< IF >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return IF;  
				}
	YY_BREAK
case 17:
YY_RULE_SETUP
<<<<<<< HEAD
#line 189 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< INT >" << std::endl;
					}
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
#line 156 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< INT >" << std::endl;
						std::cout << "INT" << std::endl;
					}
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return INT; 	
				}
	YY_BREAK
case 18:
YY_RULE_SETUP
<<<<<<< HEAD
#line 197 "../lexer/cLexer.l"
=======
#line 163 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< LONG >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return LONG; 
				}
	YY_BREAK
case 19:
YY_RULE_SETUP
<<<<<<< HEAD
#line 205 "../lexer/cLexer.l"
=======
#line 169 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< REGISTER >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return REGISTER; 
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
<<<<<<< HEAD
#line 213 "../lexer/cLexer.l"
=======
#line 175 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< RETURN >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return RETURN; 
				}
	YY_BREAK
case 21:
YY_RULE_SETUP
<<<<<<< HEAD
#line 221 "../lexer/cLexer.l"
=======
#line 181 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< SHORT >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return SHORT; 
				}
	YY_BREAK
case 22:
YY_RULE_SETUP
<<<<<<< HEAD
#line 229 "../lexer/cLexer.l"
=======
#line 187 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< SIGNED >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return SIGNED; 
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
<<<<<<< HEAD
#line 237 "../lexer/cLexer.l"
=======
#line 193 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< SIZEOF >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return SIZEOF; 
				}	
	YY_BREAK
case 24:
YY_RULE_SETUP
<<<<<<< HEAD
#line 245 "../lexer/cLexer.l"
=======
#line 199 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< STATIC >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return STATIC; 
				}
	YY_BREAK
case 25:
YY_RULE_SETUP
<<<<<<< HEAD
#line 253 "../lexer/cLexer.l"
=======
#line 205 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< STRUCT >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return STRUCT; 
				}
	YY_BREAK
case 26:
YY_RULE_SETUP
<<<<<<< HEAD
#line 261 "../lexer/cLexer.l"
=======
#line 211 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< SWITCH >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return SWITCH; 
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
<<<<<<< HEAD
#line 269 "../lexer/cLexer.l"
=======
#line 217 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< TYPEDEF >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return TYPEDEF; 
				}
	YY_BREAK
case 28:
YY_RULE_SETUP
<<<<<<< HEAD
#line 277 "../lexer/cLexer.l"
=======
#line 223 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< UNION >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return UNION; 
				}
	YY_BREAK
case 29:
YY_RULE_SETUP
<<<<<<< HEAD
#line 285 "../lexer/cLexer.l"
=======
#line 229 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< UNSIGNED >";
					}
<<<<<<< HEAD
					std::string strTemp(yytext);
   					currentSourceCodeLine += strTemp;
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return UNSIGNED; 
				}
	YY_BREAK
case 30:
YY_RULE_SETUP
<<<<<<< HEAD
#line 293 "../lexer/cLexer.l"
=======
#line 235 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< VOID >";
					}
					return VOID; 
				}
	YY_BREAK
case 31:
YY_RULE_SETUP
<<<<<<< HEAD
#line 299 "../lexer/cLexer.l"
=======
#line 241 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< VOLATILE >";
					}
					return VOLATILE; 
				}
	YY_BREAK
case 32:
YY_RULE_SETUP
<<<<<<< HEAD
#line 305 "../lexer/cLexer.l"
=======
#line 247 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< WHILE >";
					}
					return WHILE; 
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
<<<<<<< HEAD
#line 311 "../lexer/cLexer.l"
=======
#line 253 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< IDENTIFIER >";
					}

					std::string newEntry(yytext);
					table.insertNewSymbol(newEntry, yylineno);
					std::cout << "Just inserted: " << newEntry << std::endl;
					colPosition += strlen(yytext);
					symbolTableEntry* entry = table.searchTopOfStack(newEntry);
					std::cout << "name: " << entry->getIdentifierName() << std::endl; 
					yylval.entry = entry; 
					std::cout << "FROM YYLVAL: ";
					std::cout << yylval.entry->getIdentifierName() << std::endl;
					return IDENTIFIER; 				
				}
	YY_BREAK
case 34:
YY_RULE_SETUP
<<<<<<< HEAD
#line 327 "../lexer/cLexer.l"
=======
#line 269 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< INTEGER_CONSTANT >";
					}
					temp = new dVal;
					temp->dataType = INT;
					temp->value._int = atoi(yytext);
<<<<<<< HEAD
=======
					std::cout << "hi" << std::endl; 
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					yylval.val = temp;
					temp = NULL;  
					return INTEGER_CONSTANT; 						
				}
	YY_BREAK
case 35:
YY_RULE_SETUP
<<<<<<< HEAD
#line 338 "../lexer/cLexer.l"
=======
#line 281 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< FLOATING_CONSTANT >";
					}
<<<<<<< HEAD
					temp = new dVal;
					temp->dataType = FLOAT;
					temp->value._float = atof(yytext);
					yylval.val = temp;
					temp = NULL;  
=======
					/*
					yylval.dVal.dataType = FLOAT;
					yylval.dVal.value._float = atof(yytext); */
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return FLOATING_CONSTANT; 		
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
<<<<<<< HEAD
#line 349 "../lexer/cLexer.l"
=======
#line 290 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< CHARACTER_CONSTANT >";
					}
<<<<<<< HEAD
					temp = new dVal;
					temp->dataType = CHAR;
					temp->value._char = yytext[1];
					yylval.val = temp;
					temp = NULL;  
=======
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return CHARACTER_CONSTANT; 		
				}
	YY_BREAK
/* don't know what this is 
{
						if(LFLAG){
						outL << "< ENUMERATION_CONSTANT >";
					}
					return ENUMERATION_CONSTANT; 		
}
			*/
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
<<<<<<< HEAD
#line 368 "../lexer/cLexer.l"
=======
#line 304 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					std::cout << "string literal" << std::endl; 
					/* yytext??*/
					if(LFLAG){
						outL << "< STRING_LITERAL > ";
					}
					return STRING_LITERAL;
				}
	YY_BREAK
case 38:
YY_RULE_SETUP
<<<<<<< HEAD
#line 376 "../lexer/cLexer.l"
=======
#line 312 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< -> > ";
					}
					return PTR_OP;
				}
	YY_BREAK
case 39:
YY_RULE_SETUP
<<<<<<< HEAD
#line 382 "../lexer/cLexer.l"
=======
#line 318 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ++ > ";
					}
					return INC_OP;
				}
	YY_BREAK
case 40:
YY_RULE_SETUP
<<<<<<< HEAD
#line 388 "../lexer/cLexer.l"
=======
#line 324 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< -- > ";
					}
					return DEC_OP;
				}
	YY_BREAK
case 41:
YY_RULE_SETUP
<<<<<<< HEAD
#line 394 "../lexer/cLexer.l"
=======
#line 330 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< << > ";
					}
					return LEFT_OP;
				}
	YY_BREAK
case 42:
YY_RULE_SETUP
<<<<<<< HEAD
#line 400 "../lexer/cLexer.l"
=======
#line 336 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< -> > ";
					}
					return RIGHT_OP;
				}
	YY_BREAK
case 43:
YY_RULE_SETUP
<<<<<<< HEAD
#line 406 "../lexer/cLexer.l"
=======
#line 342 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< <= > ";
					}
					return LE_OP;
				}
	YY_BREAK
case 44:
YY_RULE_SETUP
<<<<<<< HEAD
#line 412 "../lexer/cLexer.l"
=======
#line 348 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< >= > ";
					}
					return GE_OP;
				}
	YY_BREAK
case 45:
YY_RULE_SETUP
<<<<<<< HEAD
#line 418 "../lexer/cLexer.l"
=======
#line 354 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< == > ";
					}
					return EQ_OP;
				}
	YY_BREAK
case 46:
YY_RULE_SETUP
<<<<<<< HEAD
#line 424 "../lexer/cLexer.l"
=======
#line 360 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< != >";
					}
					return NE_OP;
				}
	YY_BREAK
case 47:
YY_RULE_SETUP
<<<<<<< HEAD
#line 430 "../lexer/cLexer.l"
=======
#line 366 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< && >";
					}
					return AND_OP;
				}
	YY_BREAK
case 48:
YY_RULE_SETUP
<<<<<<< HEAD
#line 436 "../lexer/cLexer.l"
=======
#line 372 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< || >";
					}
					return OR_OP;
				}
	YY_BREAK
case 49:
YY_RULE_SETUP
<<<<<<< HEAD
#line 442 "../lexer/cLexer.l"
=======
#line 378 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< *= >";
					}
					return MUL_ASSIGN;
				}
	YY_BREAK
case 50:
YY_RULE_SETUP
<<<<<<< HEAD
#line 448 "../lexer/cLexer.l"
=======
#line 384 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< /= >";
					}
					return DIV_ASSIGN;
				}
	YY_BREAK
case 51:
YY_RULE_SETUP
<<<<<<< HEAD
#line 454 "../lexer/cLexer.l"
=======
#line 390 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< %= >";
					}
					return MOD_ASSIGN;
				}
	YY_BREAK
case 52:
YY_RULE_SETUP
<<<<<<< HEAD
#line 460 "../lexer/cLexer.l"
=======
#line 396 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< += >";
					}
					return ADD_ASSIGN;
				}
	YY_BREAK
case 53:
YY_RULE_SETUP
<<<<<<< HEAD
#line 466 "../lexer/cLexer.l"
=======
#line 402 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< -= >";
					}
					return SUB_ASSIGN;
				}
	YY_BREAK
case 54:
YY_RULE_SETUP
<<<<<<< HEAD
#line 472 "../lexer/cLexer.l"
=======
#line 408 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< <<= >";
					}
					return LEFT_ASSIGN;
				}
	YY_BREAK
case 55:
YY_RULE_SETUP
<<<<<<< HEAD
#line 478 "../lexer/cLexer.l"
=======
#line 414 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< >>= >";
					}
					return RIGHT_ASSIGN;
				}
	YY_BREAK
case 56:
YY_RULE_SETUP
<<<<<<< HEAD
#line 484 "../lexer/cLexer.l"
=======
#line 420 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< &= >";
					}
					return AND_ASSIGN;
				}
	YY_BREAK
case 57:
YY_RULE_SETUP
<<<<<<< HEAD
#line 490 "../lexer/cLexer.l"
=======
#line 426 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ^= >";
					}
					return XOR_ASSIGN;
				}
	YY_BREAK
case 58:
YY_RULE_SETUP
<<<<<<< HEAD
#line 496 "../lexer/cLexer.l"
=======
#line 432 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< |= >";
					}
					return XOR_ASSIGN;
				}
	YY_BREAK
case 59:
YY_RULE_SETUP
<<<<<<< HEAD
#line 502 "../lexer/cLexer.l"
=======
#line 438 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< + > ";
					} 
					return PLUS;
				}
	YY_BREAK
case 60:
YY_RULE_SETUP
<<<<<<< HEAD
#line 508 "../lexer/cLexer.l"
=======
#line 444 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< - > ";
					} 
					return MINUS;
				}
	YY_BREAK
case 61:
YY_RULE_SETUP
<<<<<<< HEAD
#line 514 "../lexer/cLexer.l"
=======
#line 450 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< * > ";
					} 
					return MULT;
				}
	YY_BREAK
case 62:
YY_RULE_SETUP
<<<<<<< HEAD
#line 520 "../lexer/cLexer.l"
=======
#line 456 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< / > ";
					} 
					return DIV;
				}
	YY_BREAK
case 63:
YY_RULE_SETUP
<<<<<<< HEAD
#line 526 "../lexer/cLexer.l"
=======
#line 462 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< % > ";
					} 
					return MOD;
				}
	YY_BREAK
case 64:
YY_RULE_SETUP
<<<<<<< HEAD
#line 532 "../lexer/cLexer.l"
=======
#line 468 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ; > ";
					} 
					return SEMI;
				}
	YY_BREAK
case 65:
YY_RULE_SETUP
<<<<<<< HEAD
#line 538 "../lexer/cLexer.l"
=======
#line 474 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< : > ";
					} 
					return COLON;
				}
	YY_BREAK
case 66:
YY_RULE_SETUP
<<<<<<< HEAD
#line 544 "../lexer/cLexer.l"
=======
#line 480 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< , > ";
					} 
					return COMMA;
				}
	YY_BREAK
case 67:
YY_RULE_SETUP
<<<<<<< HEAD
#line 550 "../lexer/cLexer.l"
=======
#line 486 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< & > ";
					} 
					return AMP;
				}
	YY_BREAK
case 68:
YY_RULE_SETUP
<<<<<<< HEAD
#line 556 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< = > ";
					}					
=======
#line 492 "../lexer/cLexer.l"
{
					if(LFLAG){
						outL << "< = > ";
					} 
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					return ASSIGN;
				}
	YY_BREAK
case 69:
YY_RULE_SETUP
<<<<<<< HEAD
#line 562 "../lexer/cLexer.l"
=======
#line 498 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ~ > ";
					} 
					return TILDE;
				}
	YY_BREAK
case 70:
YY_RULE_SETUP
<<<<<<< HEAD
#line 568 "../lexer/cLexer.l"
=======
#line 504 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< | > ";
					} 
					return PIPE;
				}
	YY_BREAK
case 71:
YY_RULE_SETUP
<<<<<<< HEAD
#line 574 "../lexer/cLexer.l"
=======
#line 510 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ^ > ";
					} 
					return CARROT;
				}
	YY_BREAK
case 72:
YY_RULE_SETUP
<<<<<<< HEAD
#line 580 "../lexer/cLexer.l"
=======
#line 516 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< . > ";
					} 
					return DOT;
				}
	YY_BREAK
case 73:
YY_RULE_SETUP
<<<<<<< HEAD
#line 586 "../lexer/cLexer.l"
=======
#line 522 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ! > ";
					} 
					return BANG;
				}
	YY_BREAK
case 74:
YY_RULE_SETUP
<<<<<<< HEAD
#line 592 "../lexer/cLexer.l"
=======
#line 528 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ? > ";
					} 
					return QUESTION;
				}
	YY_BREAK
case 75:
YY_RULE_SETUP
<<<<<<< HEAD
#line 598 "../lexer/cLexer.l"
=======
#line 534 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ( > ";
					} 
					return LPAREN;
				}
	YY_BREAK
case 76:
YY_RULE_SETUP
<<<<<<< HEAD
#line 604 "../lexer/cLexer.l"
=======
#line 540 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< [ > ";
					} 
					return LBRACK;
				}
	YY_BREAK
case 77:
YY_RULE_SETUP
<<<<<<< HEAD
#line 610 "../lexer/cLexer.l"
=======
#line 546 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< { > ";
					}
					std::cout << "PUSHING NEW LEVEL ONTO STACK" << std::endl;
					table.pushLevelOn();   
					return LCURL;
				}
	YY_BREAK
case 78:
YY_RULE_SETUP
<<<<<<< HEAD
#line 618 "../lexer/cLexer.l"
=======
#line 554 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ) > ";
					} 
					return RPAREN;
				}
	YY_BREAK
case 79:
YY_RULE_SETUP
<<<<<<< HEAD
#line 624 "../lexer/cLexer.l"
=======
#line 560 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< ] > ";
					} 
					return RBRACK;
				}
	YY_BREAK
case 80:
YY_RULE_SETUP
<<<<<<< HEAD
#line 630 "../lexer/cLexer.l"
=======
#line 566 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< } > ";
					} 
					return RCURL;
				}
	YY_BREAK
case 81:
YY_RULE_SETUP
<<<<<<< HEAD
#line 636 "../lexer/cLexer.l"
=======
#line 572 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< < > ";
					} 
					return LTHAN;
				}
	YY_BREAK
case 82:
YY_RULE_SETUP
<<<<<<< HEAD
#line 642 "../lexer/cLexer.l"
=======
#line 578 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{
					if(LFLAG){
						outL << "< > > ";
					} 
					return GTHAN;
				}
	YY_BREAK
case 83:
<<<<<<< HEAD
YY_RULE_SETUP
#line 648 "../lexer/cLexer.l"
{
					colPosition += yyleng;
				}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 651 "../lexer/cLexer.l"
{
					std::cout << "NEWLINE" << std::endl; 
=======
/* rule 83 can match eol */
YY_RULE_SETUP
#line 584 "../lexer/cLexer.l"
{
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
					if(LFLAG){
						outL << "< NEWLINE >" << std::endl;
					}
					yylineno++; 
					colPosition = 0;
<<<<<<< HEAD
					sourceCode.push_back(currentSourceCodeLine);
					std::cout << "Current source code line: " << currentSourceCodeLine << std::endl; 
					currentSourceCodeLine = ""; 
					//cout << "newline" << endl;  
				}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 663 "../lexer/cLexer.l"
=======
					//cout << "newline" << endl;  
				}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 592 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
{

					/*cout << "ERROR?" << endl; */
					/* found an illegal token, why does this output*/
					/*yyerror("Unknown token..");*/
				}		
	YY_BREAK
<<<<<<< HEAD
case 86:
YY_RULE_SETUP
#line 669 "../lexer/cLexer.l"
ECHO;
	YY_BREAK
#line 1862 "lex.yy.c"
=======
case 85:
YY_RULE_SETUP
#line 598 "../lexer/cLexer.l"
ECHO;
	YY_BREAK
#line 1787 "lex.yy.c"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
<<<<<<< HEAD
			if ( yy_current_state >= 206 )
=======
			if ( yy_current_state >= 205 )
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
<<<<<<< HEAD
		if ( yy_current_state >= 206 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 205);
=======
		if ( yy_current_state >= 205 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 204);
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

<<<<<<< HEAD
#line 669 "../lexer/cLexer.l"
=======
#line 598 "../lexer/cLexer.l"
>>>>>>> ffd37d3a3fabba50f56eb005b3dea5d31e41a238



/* user code: none for now I think.. */
